version: "3"
services:
  mostafaellethy:
    container_name: mostafaellethy
    build: .
    network_mode: bridge
    environment:
      - VIRTUAL_HOST=mostafaellethy.com
      - LETSENCRYPT_HOST=mostafaellethy.com
